### ISSUE TITLE
patch to build with MariaDB 10.2

### ISSUE THREAD

**Issue by martinkg** [horchi/scraper2vdr#2]
Trying to build vdr-scraper2vdr with the new version of MariaDB 10.2 causes a build error:

```
db.c: In member function 'int cDbConnection::errorSql(cDbConnection*, const char*, MYSQL_STMT*, const char*)':
db.c:1347:17: error: 'CR_INVALID_CONN_HANDLE' was not declared in this scope
        error == CR_INVALID_CONN_HANDLE ||
                 ^~~~~~~~~~~~~~~~~~~~~~
db.c:1347:17: note: suggested alternative: 'CR_INVALID_BUFFER_USE'
        error == CR_INVALID_CONN_HANDLE ||
                 ^~~~~~~~~~~~~~~~~~~~~~
                 CR_INVALID_BUFFER_USE
db.c:1351:17: error: 'CR_CONN_UNKNOW_PROTOCOL' was not declared in this scope
        error == CR_CONN_UNKNOW_PROTOCOL ||
                 ^~~~~~~~~~~~~~~~~~~~~~~
db.c:1351:17: note: suggested alternative: 'CR_CONN_UNKNOWN_PROTOCOL'
        error == CR_CONN_UNKNOW_PROTOCOL ||
                 ^~~~~~~~~~~~~~~~~~~~~~~
                 CR_CONN_UNKNOWN_PROTOCOL
```

In this new version of the library the define CR_CONN_UNKNOW_PROTOCOL was renamed to CR_CONN_UNKNOWN_PROTOCOL and the define CR_INVALID_CONN_HANDLE was dropped. I attached a patch proposal to fix the problem.

**Comment by martinkg** [comment]
Link to the [patch](https://bugzilla.redhat.com/attachment.cgi?id=1298509)
